# lovelace_gen

#=============================
#=== SETTINGS WEATHER SENSORS
#=============================
type: custom:button-card
name: Weather Sensors...
icon: mdi:weather-partly-cloudy
show_state: true
state_display: <elt><ha-icon icon=mdi:square-edit-outline></ha-icon></elt>
styles:
  grid:
    - grid-template-areas: '"i n s"'
    - grid-template-columns: 15% auto 5%
    - grid-template-rows: 1fr
  card:
    - height: 2em
    - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
    - font-size: 15px
    - padding: 0em 1.5em 0.5em 0.2em
    - background: none
    - box-shadow: none
  name:
    - justify-self: start
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: Weather Sensors
    hide_header: true
    card:
      type: vertical-stack
      cards:
        - type: markdown
          content: >
            For the 'Weather Outlook' you need to create the following sensor:
          style: >
            ha-card {
              font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
              font-size: 16px;
              }
        - type: markdown
          content: >
            sensor.irrigation_weather_outlook
          style: >
            ha-card {
              font-family: Monospace;
              font-size: 14px;
              text-align: center;
            }
        - type: entities
          entities:
            - type: section
              label: Rainfall Sensors (leave blank to reset default)
            - entity: input_text.irrigation_external_sensor_raining_now
              name: Raining Now
            - entity: input_text.irrigation_external_sensor_rainfall_today
              name: Rain Today
            - entity: input_text.irrigation_external_sensor_rainfall_yesterday
              name: Rain Yesterday
            - entity: input_boolean.irrigation_show_smartweather_stations
              name: Using SmartWeather (show stations)
            - type: section
              label: Temperature Sensors (leave blank to reset default)
            - entity: input_text.irrigation_external_sensor_forecast_high_temp
              name: Forecast High Temperature
            - entity: input_text.irrigation_external_sensor_current_temp
              name: Current Temperature
          style: >
            ha-card {
              font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
              }
    deviceID:
      - this
    style:
      $: |
        .mdc-dialog {
            backdrop-filter: blur(5px);
          }
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
            border-radius: 1em;
            box-shadow: 0em 0em 0.5em;
          }
