---
# Package: People/Thanh

# Person
# Enables Person Component
# https://www.home-assistant.io/integrations/person/
person:
  - name: Thanh
    id: thanh
    # user_id: 55f67b8c6c9d4ee484f4cc70f062dd5c
    device_trackers:
      - device_tracker.android_496c94b5a1133736_home_gateway

# Binary Sensors

binary_sensor:

# Input Boolean

input_boolean:
  thanh_home:
    name: Thanh at home
    icon: mdi:home-account

  thanh_bed:
    name: Thanh in bed
    icon: mdi:bed

# Sensors

sensor:
  - platform: template
    sensors:
      # device_tracker.android_496c94b5a1133736_home_gateway
      # device_tracker.oppo_r15_pro_home_gateway
      thanh_phone:
        friendly_name: Thanh's Phone
        value_template: >-
          {% if is_state('device_tracker.oppo_r15_pro_home_gateway', 'home') %}
            Online
          {% else %}
            Offline
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.oppo_r15_pro_home_gateway', 'home') %}
            mdi:cellphone-android
          {% else %}
            mdi:cellphone-off
          {% endif %}

      thanh_ipad:
        friendly_name: Thanh's iPad
        value_template: >-
          {% if is_state('device_tracker.philips_ipad_home_gateway', 'home') %}
            Online
          {% else %}
            Offline
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.philips_ipad_home_gateway', 'home') %}
            mdi:tablet-ipad
          {% else %}
            mdi:cellphone-off
          {% endif %}

      thanh_laptop:
        friendly_name: Thanh's Laptop
        value_template: >-
          {% if is_state('device_tracker.dstg158451_home_gateway', 'home') %}
            Online
          {% else %}
            Offline
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.dstg158451_home_gateway', 'home') %}
            mdi:laptop
          {% else %}
            mdi:laptop-off
          {% endif %}

# Automations

automation:
