---
# Package: Irrigation/Irrigation

# Binary Sensors

binary_sensor:
  # Binary Sensors - Template:

  - platform: template
    sensors:
      irrigation_mode:
        value_template: >-
          {% if is_state('switch.your_garage_door_sensor', 'true') %}
            Automatic
          {% else %}
            Manual
          {% endif %}
        icon_template: >-
          {% if is_state('switch.your_garage_door_sensor', 'true') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
        friendly_name: "Irrigation Mode"

# Sensors

sensor:
  # MQTT Sensor
  # https://www.home-assistant.io/integrations/sensor.mqtt/

  # Relayduino devices
  - platform: mqtt
    name: "Relayduino status"
    state_topic: "relayduino/status/mqtt"

  - platform: mqtt
    name: "Relayduino version"
    state_topic: "relayduino/status/version"

# Input Boolean
# https://www.home-assistant.io/integrations/input_boolean/

input_boolean:
  irrigation_mode_select:
    name: Automatic
    initial: true
    icon: mdi:water

  irrigation_run_manual:
    name: Run
    icon: mdi:water

  irrigation_use_master_relay:
    name: Relay
    initial: true
    icon: mdi:valve

# Counters
# Count occurrences fired by automations
# https://www.home-assistant.io/integrations/counter

counter:

# Input Datetime
# https://www.home-assistant.io/integrations/input_datetime/

input_datetime:

# Input Number
# https://www.home-assistant.io/integrations/input_number/

input_number:
  irrigation_master_relay:
    name: Irrigation Master Relay
    min: 1
    max: 8
    initial: 8
    step: 1
    mode: box
    icon: mdi:electric-switch

  irrigation_duration_manual:
    name: Duration
    min: 10
    max: 240
    initial: 10
    step: 5
    mode: slider
    unit_of_measurement: minutes
    icon: mdi:timer

# Input Select
# https://www.home-assistant.io/integrations/input_select/

input_select:
  irrigation_zone:
    name: Irrigation Zone
    options:
      - Lawn
      - Garden Beds
      - Trees
      - Vegetables
      - "OFF"
    initial: "OFF"

# Timers

# timer:

#   irrigation:
#   duration: "00:01:00"

# Automations

automation:
  - alias: Irrigation zone on
    trigger:
      platform: state
      entity_id: input_boolean.irrigation_run_manual
      from: "off"
      to: "on"
    action:
      service: mqtt.publish
      data:
        topic: relduino/control/relay
        payload: 1,1
    id: irrigation_zone_on

  - alias: Irrigation zone off
    trigger:
      platform: state
      entity_id: input_boolean.irrigation_run_manual
      from: "on"
      to: "off"
    action:
      service: mqtt.publish
      data:
        topic: relduino/control/relay
        payload: 1,1
    id: irrigation_zone_off

  - alias: Switch Irrigation Zone to Off
    trigger:
      platform: state
      entity_id: input_boolean.irrigation_mode_select
      from: "on"
      to: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.irrigation_zone
          option: "OFF"
      - service: input_boolean.turn_off
        entity_id: input_boolean.irrigation_run_manual
